apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-redis-secret
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [{{ .Values.redis.auth.existingSecret | quote }}]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-secret
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}
  apiGroup: ""
- kind: ServiceAccount
  name: "{{ .Chart.Name }}-redis"
  apiGroup: ""
roleRef:
  kind: Role
  name: read-redis-secret
  apiGroup: rbac.authorization.k8s.io
