apiVersion: v2
name: sre-challenge
description: A Helm chart for Kubernetes
type: application
version: 0.2.0

dependencies:
  - name: redis
    version: 18.1.5
    repository: https://charts.bitnami.com/bitnami
